import "./globals.css";

import { Inter } from "next/font/google";
import type { Metadata } from "next";
import { Header } from "@/components/Header";

import { incognito } from "./font/font";
import { gitlabmono } from "./font/font";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${incognito.variable} ${gitlabmono.variable} text-zinc-700`} style={{ backgroundImage: `url('/bg-noise-img.png')` }}>
        <Header />
        {children}
      </body>
    </html>
  );
}
